force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/XMLResponse__c.field-meta.xml
<CustomField>
    <fullName>XMLResponse__c</fullName>
    <description>Contains the XML data</description>
    <label>XMLResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GenerateExcel.cls
public class GenerateExcel {
    public List<ParseXML> lstParseXML{get;set;}
    String name = '';
    public GenerateExcel(){
        string candId = ApexPages.currentPage().getParameters().get('Id');
        system.debug('**CandID: **'+candId);
        Candidate__c objCand = [select Id,XMLResponse__c from Candidate__c where Id = :candId];
        lstParseXML = new List<ParseXML>();
        string xml = objCand.XMLResponse__c;
        Dom.Document doc = new Dom.Document();
        doc.load(xml);
        name = doc.getRootElement().getAttributevalue('for','');
        for(Dom.XMLNode xNode : doc.getRootElement().getChildElements()){
            integer score = Integer.valueOf(xNode.getAttributevalue('_CreditScore',''));
            string agency = xNode.getAttributeValue('_ReportingAgency','');
            lstParseXML.add(new ParseXML(agency,score));
        }
        system.debug('**List ParseXML: **'+lstParseXML);
    }
    
    public class ParseXML{
        public string agency{get;set;}
        public integer score{get;set;}
        
        public ParseXML(string agency, integer score){
            this.agency = agency;
            this.score = score;
                        
        }
    }

}