force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/XMLResponse__c.field-meta.xml
<CustomField>
    <fullName>XMLResponse__c</fullName>
    <description>Contains the XML data</description>
    <label>XMLResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AttachXMLToCandidate.cls
global class AttachXMLToCandidate {
    webservice static string GenerateExcel (string candId){
        string strMesg = '';
        system.debug('**CandID from button: **'+candId);
        Candidate__c objCand = [select Id,Name,XMLResponse__c from Candidate__c where Id = :candId];
        system.debug('**Candidate Object: **'+objCand);
            if(objCand.XMLResponse__c != null){
            system.PageReference pageRef = Page.GenerateExcelpage;
            pageRef.getParameters().put('Id',objCand.Id);
            blob body = Test.isRunningTest() ? blob.valueof('string of blob') : PageRef.getContent();
            system.debug('**Body** '+body);
            Attachment att = new Attachment();
            att.body = body;
            att.Name = 'XMLResponse'+objCand.Name+'.xls';
            att.ParentId = objCand.Id;
            insert att;
        }else{
            strMesg = 'No XML to Parse';
        }
        return strMesg;
    }

}