force-app/main/default/objects/MyAccount__c/MyAccount__c.object-meta.xml
<CustomObject>
    <description>Custom Accounts Object</description>
    <label>MyAccount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyAccount__c/fields/XMLResponse__c.field-meta.xml
<CustomField>
    <fullName>XMLResponse__c</fullName>
    <description>Contains the XML Data</description>
    <label>XMLResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GenerateEXCELForMyAct.cls
public class GenerateEXCELForMyAct {
    public List<ParseXML> lstParseXML{get;set;}
    public string name;
    public GenerateEXCELForMyAct(){
        string actId = ApexPages.currentPage().getParameters().get('Id');
        MyAccount__c objAct = [select Id,XMLResponse__c from MyAccount__c where id = : actId];
        lstParseXML = new List<ParseXML>();
        Dom.Document doc = new Dom.Document();
        doc.load(objAct.XMLResponse__c);
        name = doc.getRootElement().getAttributeValue('for','');
        for(Dom.XMLNode xNode : doc.getRootElement().getChildElements()){
            string agency = xNode.getAttributeValue('_ReportingAgency','');
            integer score = Integer.valueOf(xNode.getAttributeValue('_CreditScore',''));
            lstParseXML.add(new ParseXML(agency,score));
            system.debug('**lstParseXML**'+lstParseXML);
            system.debug('**agency**'+agency);
            system.debug('**score**'+score);
        }
        
    }
    
    public class ParseXML{
        public string agency{get;set;}
        public integer score{get;set;}
        
        public ParseXML(string agency, integer score){
            this.agency = agency;
            this.score = score;
        }
    }
}