force-app/main/default/objects/MyAccount__c/MyAccount__c.object-meta.xml
<CustomObject>
    <description>Custom Accounts Object</description>
    <label>MyAccount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyAccount__c/fields/XMLResponse__c.field-meta.xml
<CustomField>
    <fullName>XMLResponse__c</fullName>
    <description>Contains the XML Data</description>
    <label>XMLResponse</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AttachExcelToMyAccount.cls
global class AttachExcelToMyAccount {
    webservice static string GenerateExcel(string actId){
        string strMesg = '';
        MyAccount__c objAct = [select id,Name,XMLResponse__c from MyAccount__c where id =:actId];
        if(objAct.XMLResponse__c != null){
            system.PageReference PageRef = Page.GenerateEXCELForMyAct;
            PageRef.getParameters().put('Id',objAct.Id);
            Blob body = Test.isRunningTest() ? Blob.valueOf('String toBlob') : PageRef.getContent();
            Attachment att = new Attachment();
            att.body = body;
            att.Name = 'XML Response'+objAct.Name+'.xls';
            att.ParentId = objAct.Id;
            insert att;
        }else{
            return 'No XML to Parse';
        }
        return strMesg;
    }
}